In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import dabench as dab
import numpy as np
import jax
from timeit import default_timer as timer
import pandas as pd
import pickle
import os

# Set up

### Read-in Raytune Results

In [3]:
raytune_system_dim_results = pd.read_csv('./out_rev/l96/raytune_l96_v2.csv')
raytune_system_dim_results['trialnum'] = raytune_system_dim_results.index
raytune_system_dim_results.index = np.arange(raytune_system_dim_results.shape[0])
rows_to_get = raytune_system_dim_results.groupby(['system_dim']).idxmin(numeric_only=True)['rmse']
best_results_system_dim = raytune_system_dim_results.loc[rows_to_get]

In [4]:
raytune_heatmap_results = pd.read_csv('./out_rev/l96/raytune_l96_heatmap_v2.csv')
raytune_heatmap_results['trialnum'] = raytune_heatmap_results.index
raytune_heatmap_results.index = np.arange(raytune_heatmap_results.shape[0])
rows_to_get = raytune_heatmap_results.groupby(['num_obs','obs_sd']).idxmin(numeric_only=True)['rmse']
best_results_heatmap = raytune_heatmap_results.loc[rows_to_get]

### Define parameters

In [5]:
system_dim= 36
spinup_size = 14400
valid_size = 5000
transient_size = 1000
test_size = 5000
nr_steps = spinup_size + valid_size + transient_size + test_size
delta_t=0.01
obs_sd = 0.5
sigma_obs = obs_sd *1.25
analysis_window = 0.1
analysis_time_in_window = 0.0
obs_location_count = 18
num_iters = 3
n_outer_loops = 3
num_runs = 1
output_suffix='v2'

### Function definition: Backprop 4DVar

We'll need to prep and run Backprop-4DVar many times, so this wraps it all into one function

In [6]:
def calc_background_cov(enkf_run_pkl):
    with open(enkf_run_pkl, 'rb') as f: 
        etkf_run = pickle.load(f) 
    system_dim = etkf_run.values.shape[-1]
    etkf_errors = np.moveaxis(etkf_run.values, (0,1,2), (1,0,2)) - np.mean(etkf_run.values, axis=1)
    etkf_errors = etkf_errors[:,-5000:]
    etkf_errors = etkf_errors[:,np.arange(9,5000,10)]
    B = np.cov(etkf_errors.reshape(system_dim, -1))
    return B

In [7]:
def run_backprop_4dvar(system_dim, nr_steps, spinup_size, valid_size, transient_size, test_size, 
                       test_run, delta_t, obs_location_count, obs_sd, sigma_bg_multiplier, 
                       sigma_obs, analysis_window, analysis_time_in_window, 
                       random_seed, num_iters, learning_rate, lr_decay):
    enkf_run_pkl = './out_rev/l96/l96_enkf_statevec_{}dim_v1.pkl'.format(system_dim)
    np_rng = np.random.default_rng(random_seed)
    jax.clear_caches()

    ### Nature Run
    nature_run = dab.data.Lorenz96(system_dim=system_dim, delta_t=delta_t,
                                   store_as_jax=True, random_seed=random_seed)

    x0_initial = np_rng.normal(size=system_dim, scale=1)
    nature_run.generate(n_steps=nr_steps, x0 = x0_initial) 
    nr_spinup, nr_valid, nr_transient_and_test = nature_run.split_train_valid_test(
        spinup_size, valid_size, transient_size + test_size)
    nr_transient, nr_test, _ = nr_transient_and_test.split_train_valid_test(
        transient_size, test_size, 0)

    if not test_run:
        nr_eval = nr_valid
    else:
        nr_eval = nr_test


    ### Observations
    obs_l96 = dab.observer.Observer(
        nr_eval,
        time_indices = np.arange(0, nr_eval.time_dim, 5),
        random_location_count = obs_location_count,
        error_bias = 0.0,
        error_sd = obs_sd,
        random_seed=random_seed,
        stationary_observers=True,
        store_as_jax=True
    )
    obs_vec_l96 = obs_l96.observe()

    
    ### Forecast Model
    model_l96 = dab.data.Lorenz96(system_dim=system_dim, delta_t=delta_t, 
                                  store_as_jax=True, random_seed=random_seed)

    class L96Model(dab.model.Model):                                                                       
        """Defines model wrapper for Lorenz96 to test forecasting."""
        def forecast(self, state_vec, n_steps):
            self.model_obj.generate(x0=state_vec.values, n_steps=n_steps)
            new_vals = self.model_obj.values 

            new_vec = dab.vector.StateVector(values=new_vals, store_as_jax=True)

            return new_vec

    fc_model = L96Model(model_obj=model_l96)
    
    ### Set up DA matrices: H (observation), R (obs error), B (background error)
    H = np.zeros((obs_location_count, system_dim))
    H[np.arange(H.shape[0]), obs_vec_l96.location_indices[0]] = 1
    R = (sigma_obs**2)* np.identity(obs_location_count)
    B = sigma_bg_multiplier*calc_background_cov(enkf_run_pkl) 

    
    ### Run data assimilation
    da_time_start = timer()
    
    # Prep DA object
    dc = dab.dacycler.Var4DBackprop(
        system_dim=system_dim,
        delta_t=nr_eval.delta_t,
        H=H,
        B=B,
        R=R,
        num_iters=num_iters,
        loss_growth_limit=1000,
        learning_rate=learning_rate,
        lr_decay=lr_decay,
        model_obj=fc_model,
        obs_window_indices=[0,5,10],
        steps_per_window=11, # 11 instead of 10 because inclusive of 0 and 11
        )

    # Generate initial conditions
    cur_tstep = 0
    x0_original = nr_eval.values[cur_tstep] + np_rng.normal(size=(system_dim,), 
                                                            scale=np.diag(B))
    x0_sv = dab.vector.StateVector(
        values=x0_original,
        store_as_jax=True)
    
    # Execute
    out_statevec = dc.cycle(
        input_state = x0_sv,
        start_time = nr_eval.times[cur_tstep],
        obs_vector = obs_vec_l96,
        analysis_window=analysis_window,
        n_cycles=498,
        return_forecast=True,
        obs_error_sd=sigma_obs,
        analysis_time_in_window=analysis_time_in_window)
    
    da_time = timer()-da_time_start
    rmse = np.sqrt(np.mean(np.square(nr_eval.values[:-20] - out_statevec.values)))
    
    return out_statevec, rmse, obs_vec_l96, nr_eval, da_time

### Function: 4DVar

In [8]:
def run_4dvar(system_dim, nr_steps, spinup_size, valid_size, transient_size, test_run, 
              test_size, delta_t, obs_location_count, obs_sd, sigma_bg_multiplier, sigma_obs,
              analysis_window, analysis_time_in_window, random_seed, n_outer_loops):
    enkf_run_pkl = './out_rev/l96/l96_enkf_statevec_{}dim_v1.pkl'.format(system_dim)
    np_rng = np.random.default_rng(random_seed)
    jax.clear_caches()

    ### Nature Run
    nature_run = dab.data.Lorenz96(system_dim=system_dim, delta_t=delta_t,
                                   store_as_jax=True, random_seed=random_seed)

    x0_initial = np_rng.normal(size=system_dim, scale=1)
    nature_run.generate(n_steps=nr_steps, x0 = x0_initial) 
    nr_spinup, nr_valid, nr_transient_and_test = nature_run.split_train_valid_test(
        spinup_size, valid_size, transient_size + test_size)
    nr_transient, nr_test, _ = nr_transient_and_test.split_train_valid_test(
        transient_size, test_size, 0)

    if not test_run:
        nr_eval = nr_valid
    else:
        nr_eval = nr_test


    ### Observations
    obs_l96 = dab.observer.Observer(
        nr_eval,
        time_indices = np.arange(0, nr_eval.time_dim, 5),
        random_location_count = obs_location_count,
        error_bias = 0.0,
        error_sd = obs_sd,
        random_seed=random_seed,
        stationary_observers=True,
        store_as_jax=True
    )
    obs_vec_l96 = obs_l96.observe()

    
    ### Forecast Model
    model_l96 = dab.data.Lorenz96(system_dim=system_dim, delta_t=delta_t, 
                                  store_as_jax=True, random_seed=random_seed)
    class L96Model(dab.model.Model):                                                                       
        """Defines model wrapper for Lorenz96 to test forecasting."""
        def forecast(self, state_vec,n_steps):
            self.model_obj.generate(x0=state_vec.values, n_steps=n_steps)
            new_vals = self.model_obj.values 

            new_vec = dab.vector.StateVector(values=new_vals, store_as_jax=True)

            return new_vec

        def compute_tlm(self, state_vec, n_steps):
            """For 4DVar. Not used for Backprop4DVar"""
            M = self.model_obj.generate(n_steps=n_steps, x0=state_vec.values,
                                        return_tlm=True)
            return M, self.model_obj.values

    fc_model = L96Model(model_obj=model_l96)
    
    ### Set up DA matrices
    
    ### Set up DA matrices: H (observation), R (obs error), B (background error)
    H = np.zeros((obs_location_count, system_dim))
    H[np.arange(H.shape[0]), np.tile(obs_vec_l96.location_indices[0], 1)] = 1
    R = (sigma_obs**2) * np.identity(obs_location_count)
    B = sigma_bg_multiplier*calc_background_cov(enkf_run_pkl) 
    
    ### Run data assimilation
    da_time_start = timer()
    
    # Prep DA object
    dc = dab.dacycler.Var4D(
        system_dim=system_dim,
        delta_t=nature_run.delta_t,
        H=H,
        B=B,
        R=R,
        n_outer_loops=n_outer_loops,
        model_obj=fc_model,
        obs_window_indices=[0,5, 10],
        steps_per_window=11, # 11 instead of 10 because inclusive of 0 and 11
    )
    
    # Generate initial conditions
    cur_tstep = 0
    x0_original = nr_eval.values[cur_tstep] + np_rng.normal(size=(system_dim,), 
                                                            scale=np.diag(B))
    x0_sv = dab.vector.StateVector(
        values=x0_original,
        store_as_jax=True)
    
    # Execute
    out_statevec_4dvar = dc.cycle(
        input_state = x0_sv,
        start_time = nr_eval.times[cur_tstep],
        obs_vector = obs_vec_l96,
        analysis_window=analysis_window,
        n_cycles=498,
        return_forecast=True,
        obs_error_sd=sigma_obs,
        analysis_time_in_window=analysis_time_in_window)
    
    da_time = timer()-da_time_start
    rmse = np.sqrt(np.mean(np.square(nr_eval.values[:-20] - out_statevec_4dvar.values)))
    
    return out_statevec_4dvar, rmse, obs_vec_l96, nr_eval, da_time

### Function: Baserun (no DA)

In [9]:
def run_baserun(system_dim, nr_steps, spinup_size, valid_size, transient_size, test_run,
                test_size, delta_t, random_seed, sigma_bg_multiplier):
    enkf_run_pkl = './out_rev/l96/l96_enkf_statevec_{}dim_v1.pkl'.format(system_dim)
    np_rng = np.random.default_rng(random_seed)
    jax.clear_caches()


    ### Nature Run
    nature_run = dab.data.Lorenz96(system_dim=system_dim, delta_t=delta_t, 
                                   store_as_jax=True, random_seed=random_seed)
    x0_initial = np_rng.normal(size=system_dim, scale=1)
    nature_run.generate(n_steps=nr_steps, x0 = x0_initial)
    
    nr_spinup, nr_valid, nr_transient_and_test = nature_run.split_train_valid_test(
        spinup_size, valid_size, transient_size + test_size)
    nr_transient, nr_test, _ = nr_transient_and_test.split_train_valid_test(
        transient_size, test_size, 0)

    if not test_run:
        nr_eval = nr_valid
    else:
        nr_eval = nr_test
  
    ### Forecast Model
    model_l96 = dab.data.Lorenz96(system_dim=system_dim, delta_t=delta_t,
                                  store_as_jax=True, random_seed=random_seed)


    ### Run
    da_time_start = timer()
    cur_tstep = 0
    B = sigma_bg_multiplier*calc_background_cov(enkf_run_pkl) 
    x0_original = nr_eval.values[cur_tstep] + np_rng.normal(size=(system_dim,), 
                                                            scale=np.diagonal(B))
    
    model_l96.generate(x0=x0_original, n_steps=nr_eval.time_dim)
    
    rmse = np.sqrt(np.mean(np.square(model_l96.values[:-20] - nr_eval.values[:-20])))
    da_time = timer()-da_time_start
    out_vec = dab.vector.StateVector(values=model_l96.values, times=model_l96.times, store_as_jax=True)
    
    return out_vec, rmse, nr_eval, da_time

# Run on Validation

### System size experiments - Validation Set

In [ ]:
# Backprop 4D Var w/ Approximate Hessian
out_dict_list_bp = []
random_seed_list = np.arange(num_runs)
system_dim_list = [6, 20, 36, 72, 144, 256]

for system_dim in system_dim_list:
    
    obs_location_count = int(system_dim/2)
    best_results_filtered = best_results_system_dim.loc[
        best_results_system_dim['system_dim']==system_dim]
    learning_rate = best_results_filtered['config/lr'].values[0]
    lr_decay = best_results_filtered['config/lr_decay'].values[0]

    for i in range(num_runs):
        
        random_seed = system_dim + random_seed_list[i]
        
        run_dict = dict(
            system_dim=system_dim, 
            nr_steps= nr_steps,
            spinup_size=spinup_size,
            valid_size=valid_size,
            transient_size=transient_size,
            test_size=test_size,
            test_run=False,
            delta_t=delta_t,
            obs_location_count=obs_location_count,
            obs_sd=obs_sd,
            sigma_bg_multiplier=5*obs_sd,
            sigma_obs=sigma_obs,
            analysis_window=analysis_window,
            analysis_time_in_window=analysis_time_in_window,
            random_seed=random_seed,
            num_iters=num_iters,
            learning_rate=learning_rate,
            lr_decay = lr_decay) 
        out_bp, error_bp, obs_vec_l96, nr_eval, da_time = run_backprop_4dvar(**run_dict)
        
        run_dict['time'] = da_time 
        run_dict['rmse'] = error_bp
        run_dict['run_num'] = i
        print('Run {}, Time = {}'.format(i,run_dict['time']))
        out_dict_list_bp.append(run_dict)
        
bp_df_time =  pd.DataFrame(out_dict_list_bp)
bp_df_time.to_csv('./out_rev/l96/bp_systemdim_val_{}.csv'.format(output_suffix))

In [11]:
# 4D Var
out_dict_list_4dvar = []

random_seed_list = np.arange(num_runs)
system_dim_list = [6, 20, 36, 72, 144, 256]

for system_dim in system_dim_list:
    
    for i in range(num_runs):
        
        obs_location_count = int(system_dim/2)
        random_seed = system_dim + random_seed_list[i]
        
        run_dict = dict(system_dim=system_dim, 
            nr_steps=nr_steps,
            spinup_size=spinup_size,
            valid_size=valid_size,
            transient_size=transient_size,
            test_size=test_size,
            test_run=False,
            delta_t=delta_t,
            obs_location_count=obs_location_count,
            obs_sd=obs_sd,
            sigma_bg_multiplier=5*obs_sd,
            sigma_obs=sigma_obs,
            analysis_window=analysis_window,
            analysis_time_in_window=analysis_time_in_window,
            random_seed=random_seed,
            n_outer_loops = n_outer_loops)
        
        out_4dvar, error_4dvar, obs_vec_l96, nr_eval, da_time = run_4dvar(**run_dict)
        run_dict['time'] = da_time
        run_dict['rmse'] = error_4dvar
        run_dict['run_num'] = i
        
        print('Run {}, Time = {}'.format(i,run_dict['time']))
        out_dict_list_4dvar.append(run_dict)
        
var4d_df_time =  pd.DataFrame(out_dict_list_4dvar)
var4d_df_time.to_csv('./out_rev/l96/var4d_systemdim_val_{}.csv'.format(output_suffix))

Run 0, Time = 7.439323276000096
Run 0, Time = 8.281533513999989
Run 0, Time = 10.264803503999929
Run 0, Time = 19.419301095000037
Run 0, Time = 56.91310063000003
Run 0, Time = 155.4301503920001

In [12]:

bp_df_time[['system_dim','time','rmse']].groupby('system_dim').mean()

                 time      rmse
system_dim
6            9.844868  0.411135
20           8.099211  0.459486
36           7.848270  0.397172
72           8.106770  0.820750
144          8.271580  0.950730
256         10.423639  0.972403

In [13]:

var4d_df_time[['system_dim','time','rmse']].groupby('system_dim').mean()

                  time      rmse
system_dim
6             7.439323  0.664313
20            8.281534  0.564881
36           10.264804  0.462790
72           19.419301  0.793372
144          56.913101  0.921575
256         155.430150  0.945843

### Experiments varying number of observations and obs error - Validation Set

In [14]:
# Backprop 4D Var w/ Approximate Hessian
out_dict_list_bp_obs = []

num_iters=3
system_dim = 36
random_seed = system_dim
num_obs_list = [6, 12, 18, 24, 30, 36]
obs_error_list = [0.1, 0.2, 0.3, 0.4, 0.5, 0.75, 1.0, 1.5, 2.0]

for obs_location_count in num_obs_list:
    for obs_sd in obs_error_list:
        
        best_results_filtered = best_results_heatmap.loc[
            (best_results_heatmap['obs_sd'].round(2)==round(obs_sd, 2)) & 
            (best_results_heatmap['num_obs']==obs_location_count)]
        learning_rate = best_results_filtered['config/lr'].values[0]
        lr_decay = best_results_filtered['config/lr_decay'].values[0]
        
        for i in range(num_runs):
            run_dict = dict(system_dim=system_dim, 
                nr_steps=nr_steps,
                spinup_size=spinup_size,
                valid_size=valid_size,
                transient_size=transient_size,
                test_size=test_size,
                test_run=False,
                delta_t=delta_t,
                obs_location_count=obs_location_count,
                obs_sd=obs_sd,
                sigma_bg_multiplier=5*obs_sd,
                sigma_obs=obs_sd*1.25,
                analysis_window=analysis_window,
                analysis_time_in_window=analysis_time_in_window,
                random_seed=random_seed,
                num_iters=num_iters,
                learning_rate=learning_rate,
                lr_decay=lr_decay)
            
            out_bp, error_bp, obs_vec_l96, nature_run, da_time = run_backprop_4dvar(**run_dict)
            run_dict['time'] = da_time
            run_dict['rmse'] = error_bp
            run_dict['run_num'] = i
            
            print('Run {}, Time = {}'.format(i,run_dict['time']))
            print(obs_location_count, obs_sd, error_bp)
            out_dict_list_bp_obs.append(run_dict)
            
bp_df_obs =  pd.DataFrame(out_dict_list_bp_obs)
bp_df_obs.to_csv('./out_rev/l96/bp_heatmap_val_{}.csv'.format(output_suffix))

Run 0, Time = 8.155514337
6 0.1 3.527367827332716
Run 0, Time = 7.549444963000042
6 0.2 3.526097344362216
Run 0, Time = 8.013145010000017
6 0.3 3.5518560383182227
Run 0, Time = 7.799334356000031
6 0.4 3.6461219324281156
Run 0, Time = 8.12245957999994
6 0.5 3.727740382987345
Run 0, Time = 7.7689600219999875
6 0.75 3.665815636053805
Run 0, Time = 7.805517397000017
6 1.0 3.798091098867156
Run 0, Time = 7.9988638700000365
6 1.5 4.035668717598643
Run 0, Time = 8.002264056000058
6 2.0 4.17021680071887
Run 0, Time = 8.040849258000094
12 0.1 0.6214560966698023
Run 0, Time = 7.686284814000032
12 0.2 1.1735491145682941
Run 0, Time = 8.067776934999983
12 0.3 1.1428448011675825
Run 0, Time = 7.916562366999983
12 0.4 1.6419404068767274
Run 0, Time = 8.065040930999999
12 0.5 1.9623525837898705
Run 0, Time = 7.774395375999916
12 0.75 1.9646932191204685
Run 0, Time = 8.120785591000072
12 1.0 2.284174895988646
Run 0, Time = 7.658006453000098
12 1.5 2.9604521020764034
Run 0, Time = 7.444949548000068
12 2.0 3.0608567394720376
Run 0, Time = 8.138028512999995
18 0.1 0.12166630311144126
Run 0, Time = 7.596020701000043
18 0.2 0.20234172453206395
Run 0, Time = 7.740489341000057
18 0.3 0.2529311486903696
Run 0, Time = 7.75361052400001
18 0.4 0.38189851842049727
Run 0, Time = 8.105767433999972
18 0.5 0.397172109546703
Run 0, Time = 7.437953469999911
18 0.75 0.6634832415427617
Run 0, Time = 7.824871606999977
18 1.0 1.1812975204091036
Run 0, Time = 7.72681014900013
18 1.5 1.595389576527589
Run 0, Time = 7.77101738500005
18 2.0 2.1920834315489937
Run 0, Time = 9.438139928000055
24 0.1 0.08792366029921077
Run 0, Time = 8.463870806999921
24 0.2 0.15983410980726592
Run 0, Time = 7.487676788999806
24 0.3 0.42367722952938464
Run 0, Time = 7.607494508999935
24 0.4 0.5215535859065784
Run 0, Time = 7.4386157380001805
24 0.5 0.6323851535090159
Run 0, Time = 7.942252526999937
24 0.75 0.7826846952788526
Run 0, Time = 7.806656588999886
24 1.0 0.8680296153129032
Run 0, Time = 7.904145884000172
24 1.5 1.3750303908197028
Run 0, Time = 8.052882357000044
24 2.0 1.5285814643148086
Run 0, Time = 8.023018460999992
30 0.1 0.06562992873673101
Run 0, Time = 8.155970744999877
30 0.2 0.1385372357984576
Run 0, Time = 7.95937859799983
30 0.3 0.1629590750074565
Run 0, Time = 8.00954528300008
30 0.4 0.24263471413012683
Run 0, Time = 7.510815051999998
30 0.5 0.276487757448627
Run 0, Time = 7.539421001999926
30 0.75 0.3789443427849987
Run 0, Time = 8.25698545399996
30 1.0 0.4794466453943322
Run 0, Time = 8.289662432000114
30 1.5 0.6998202381536384
Run 0, Time = 8.333656294999855
30 2.0 0.9878907223945327
Run 0, Time = 8.124629034999998
36 0.1 0.155736345755131
Run 0, Time = 8.01330490600003
36 0.2 0.08334391252304148
Run 0, Time = 7.702028634999806
36 0.3 0.14375550482135652
Run 0, Time = 8.275562581000031
36 0.4 0.21727657082939394
Run 0, Time = 8.170169482999881
36 0.5 0.19898984181337603
Run 0, Time = 8.433217748000061
36 0.75 0.29916419690386326
Run 0, Time = 8.160241054000153
36 1.0 0.36534759119292665
Run 0, Time = 7.739028658000052
36 1.5 0.5434353841406172
Run 0, Time = 8.202921982000134
36 2.0 0.7625410939147901

In [15]:
# 4D Var

out_dict_list_4dvar_obs = []

system_dim = 36
random_seed = system_dim
num_obs_list = [6, 12, 18, 24, 30, 36]
obs_error_list = [0.1, 0.2, 0.3, 0.4, 0.5, 0.75, 1.0, 1.5, 2.0]

for obs_location_count in num_obs_list:
    for obs_sd in obs_error_list:
        for i in range(num_runs):
            
            run_dict = dict(system_dim=system_dim, 
                nr_steps=nr_steps,
                spinup_size=spinup_size,
                valid_size=valid_size,
                transient_size=transient_size,
                test_size=test_size,
                test_run=False,
                delta_t=delta_t,
                obs_location_count=obs_location_count,
                obs_sd=obs_sd,
                sigma_bg_multiplier=5*obs_sd,
                sigma_obs=obs_sd*1.25,
                analysis_window=analysis_window,
                analysis_time_in_window=analysis_time_in_window,
                random_seed=random_seed,
                n_outer_loops = n_outer_loops)
            
            out_4dvar, error_4dvar, obs_vec_l96, nature_run, da_time = run_4dvar(**run_dict)
            run_dict['time'] = da_time
            run_dict['rmse'] = error_4dvar
            run_dict['run_num'] = i
            
            print('Run {}, Time = {}'.format(i,run_dict['time']))
            out_dict_list_4dvar_obs.append(run_dict)
            
var4d_df_obs =  pd.DataFrame(out_dict_list_4dvar_obs)
var4d_df_obs.to_csv('./out_rev/l96/var4d_heatmap_val_{}.csv'.format(output_suffix))

Run 0, Time = 10.272369492000053
Run 0, Time = 9.973740922999923
Run 0, Time = 10.337218704999941
Run 0, Time = 10.352962537999929
Run 0, Time = 10.34185001700007
Run 0, Time = 13.518707373000098
Run 0, Time = 11.534863974000018
Run 0, Time = 10.444672313999945
Run 0, Time = 9.769151059000023
Run 0, Time = 10.916559014000086
Run 0, Time = 10.588333597999963
Run 0, Time = 10.370309210999949
Run 0, Time = 10.284058529000049
Run 0, Time = 10.574778471999934
Run 0, Time = 9.988885477000167
Run 0, Time = 10.014318756999955
Run 0, Time = 10.681528258999833
Run 0, Time = 10.185547991000021
Run 0, Time = 11.010830292000037
Run 0, Time = 10.417183695999938
Run 0, Time = 10.130755069000088
Run 0, Time = 10.863737479000065
Run 0, Time = 10.355201555999884
Run 0, Time = 10.278073145000008
Run 0, Time = 10.569839234000028
Run 0, Time = 10.399468636000165
Run 0, Time = 10.503398512999865
Run 0, Time = 10.996139847999984
Run 0, Time = 10.162223186999881
Run 0, Time = 10.676058927999975
Run 0, Time = 10.12909128199999
Run 0, Time = 10.762550782000062
Run 0, Time = 10.684039798999947
Run 0, Time = 10.335496180000064
Run 0, Time = 10.687428834000002
Run 0, Time = 10.349573671999906
Run 0, Time = 10.758842868999864
Run 0, Time = 11.101535497999976
Run 0, Time = 10.868948709999813
Run 0, Time = 11.208627493999984
Run 0, Time = 10.489573113999995
Run 0, Time = 10.747831756000096
Run 0, Time = 10.6643633220001
Run 0, Time = 10.402888298000107
Run 0, Time = 10.622248544000058
Run 0, Time = 10.631242241000109
Run 0, Time = 11.005666470000051
Run 0, Time = 10.745603908000021
Run 0, Time = 10.982912366000164
Run 0, Time = 10.46402398500004
Run 0, Time = 11.022699281000087
Run 0, Time = 10.661566901000015
Run 0, Time = 10.422248073999981
Run 0, Time = 10.558748617999754

# Repeating everything on the test set

### System Size Experiments - Test Set

In [10]:
num_runs =  50

In [11]:
# Backprop 4D Var w/ Approximate Hessian

out_dict_list_bp = []

random_seed_list = np.arange(num_runs)+102
system_dim_list = [6, 20, 36, 72, 144, 256]

for system_dim in system_dim_list:
    
    obs_location_count = int(system_dim/2)
    best_results_filtered = best_results_system_dim.loc[best_results_system_dim['system_dim']==system_dim]
    learning_rate = best_results_filtered['config/lr'].values[0]
    lr_decay = best_results_filtered['config/lr_decay'].values[0]

    for i in range(num_runs):
        
        random_seed = system_dim + random_seed_list[i]
        
        run_dict = dict(
            system_dim=system_dim, 
            nr_steps= nr_steps,
            spinup_size=spinup_size,
            valid_size=valid_size,
            transient_size=transient_size,
            test_size=test_size,
            test_run=True,
            delta_t=delta_t,
            obs_location_count=obs_location_count,
            obs_sd=obs_sd,
            sigma_bg_multiplier=5*obs_sd,
            sigma_obs=sigma_obs,
            analysis_window=analysis_window,
            analysis_time_in_window=analysis_time_in_window,
            random_seed=random_seed,
            num_iters=num_iters,
            learning_rate=learning_rate,
            lr_decay = lr_decay)
        
        out_bp, error_bp, obs_vec_l96, nr_eval, da_time = run_backprop_4dvar(**run_dict)
        
        run_dict['time'] = da_time 
        run_dict['rmse'] = error_bp
        run_dict['run_num'] = i
        print('Run {}, Time = {}'.format(i,run_dict['time']))
        out_dict_list_bp.append(run_dict)
        
bp_df_time =  pd.DataFrame(out_dict_list_bp)
bp_df_time.to_csv('./out_rev/l96/bp_systemdim_test_{}.csv'.format(output_suffix))

Run 0, Time = 9.749508412000012
Run 1, Time = 9.965020732000028
Run 2, Time = 10.292765194999959
Run 3, Time = 8.779446807
Run 4, Time = 7.206264593000014
Run 5, Time = 7.207802370999957
Run 6, Time = 7.109483613000009
Run 7, Time = 7.283279720000053
Run 8, Time = 7.3039053069999795
Run 9, Time = 7.201072944000032
Run 10, Time = 7.312599927000065
Run 11, Time = 7.191181712000002
Run 12, Time = 7.338236217000031
Run 13, Time = 7.134680254000045
Run 14, Time = 7.128238790999944
Run 15, Time = 7.183645100000035
Run 16, Time = 7.43621765499995
Run 17, Time = 7.47840209900005
Run 18, Time = 7.452891131000001
Run 19, Time = 7.494407549000016
Run 20, Time = 7.136114699000018
Run 21, Time = 7.327622748999943
Run 22, Time = 7.598913369999991
Run 23, Time = 7.346124463000024
Run 24, Time = 7.278294302999939
Run 25, Time = 7.2713864520000016
Run 26, Time = 7.405388463000008
Run 27, Time = 7.489632447999952
Run 28, Time = 7.071741492000001
Run 29, Time = 7.349974650999911
Run 30, Time = 7.1194442690000415
Run 31, Time = 7.2888925759999665
Run 32, Time = 7.122630652999987
Run 33, Time = 7.489139036000097
Run 34, Time = 7.201120570000057
Run 35, Time = 7.069035514999996
Run 36, Time = 7.120061904999943
Run 37, Time = 7.280519314000003
Run 38, Time = 7.136566401999971
Run 39, Time = 7.147298842000055
Run 40, Time = 7.184412921999979
Run 41, Time = 7.137817907999988
Run 42, Time = 7.528839196999911
Run 43, Time = 7.230658955999957
Run 44, Time = 6.995189718999995
Run 45, Time = 7.149308087999998
Run 46, Time = 7.032160127999987
Run 47, Time = 7.2556871029999
Run 48, Time = 7.174379130000034
Run 49, Time = 7.528499896000085
Run 0, Time = 7.897630313000036
Run 1, Time = 7.85958830200002
Run 2, Time = 7.929522239000107
Run 3, Time = 7.778915243000029
Run 4, Time = 7.654349970999988
Run 5, Time = 7.741557874999899
Run 6, Time = 7.629808761000049
Run 7, Time = 7.803821735000042
Run 8, Time = 7.596143536
Run 9, Time = 8.095670442000028
Run 10, Time = 7.7016419320000296
Run 11, Time = 8.154036482000038
Run 12, Time = 7.966973787000029
Run 13, Time = 7.845834494999963
Run 14, Time = 7.402134637000017
Run 15, Time = 7.680821481000066
Run 16, Time = 7.920448673999999
Run 17, Time = 7.897579537000183
Run 18, Time = 8.075300996000124
Run 19, Time = 8.31337918600002
Run 20, Time = 7.526518418000023
Run 21, Time = 7.6231605059999765
Run 22, Time = 7.702933497999993
Run 23, Time = 8.113582733000158
Run 24, Time = 8.192959237999958
Run 25, Time = 7.632507788000112
Run 26, Time = 7.44369739800004
Run 27, Time = 7.999966277000112
Run 28, Time = 8.215703893999944
Run 29, Time = 8.082385048999868
Run 30, Time = 7.8638537180002
Run 31, Time = 7.408146397999872
Run 32, Time = 7.67287972500003
Run 33, Time = 7.90857033400016
Run 34, Time = 7.677447804000167
Run 35, Time = 7.574219849999963
Run 36, Time = 8.100149972000054
Run 37, Time = 7.93806903199993
Run 38, Time = 8.089390065000089
Run 39, Time = 7.787958962000175
Run 40, Time = 8.19513724300009
Run 41, Time = 8.035353369999939
Run 42, Time = 7.555580688999953
Run 43, Time = 7.88555304700003
Run 44, Time = 8.100817772000028
Run 45, Time = 7.925433115000033
Run 46, Time = 7.587431771999945
Run 47, Time = 7.725105820999943
Run 48, Time = 7.989450971999986
Run 49, Time = 7.607839283999965
Run 0, Time = 8.353542222999977
Run 1, Time = 8.24776717199984
Run 2, Time = 8.038341004999893
Run 3, Time = 8.402138856999954
Run 4, Time = 8.490462683000032
Run 5, Time = 7.625317942000038
Run 6, Time = 8.489720201999944
Run 7, Time = 8.480974371999991
Run 8, Time = 8.054120155999954
Run 9, Time = 8.287976673000003
Run 10, Time = 8.195986753999932
Run 11, Time = 8.158298637999906
Run 12, Time = 8.337684127999864
Run 13, Time = 8.204367870999931
Run 14, Time = 7.863567515000113
Run 15, Time = 8.268853454999999
Run 16, Time = 8.157598059000065
Run 17, Time = 7.8156834619999245
Run 18, Time = 8.233236330999944
Run 19, Time = 8.117362493999963
Run 20, Time = 7.83270117699999
Run 21, Time = 8.07189409900002
Run 22, Time = 8.18277416900014
Run 23, Time = 8.281388428000128
Run 24, Time = 8.321453229000099
Run 25, Time = 8.113400834000004
Run 26, Time = 8.59546219799995
Run 27, Time = 8.542810315999986
Run 28, Time = 7.712939012999868
Run 29, Time = 8.454899037000132
Run 30, Time = 8.063269090000176
Run 31, Time = 8.119723598999826
Run 32, Time = 8.424856684999895
Run 33, Time = 8.102198905000023
Run 34, Time = 8.795086814000115
Run 35, Time = 8.21680987700006
Run 36, Time = 8.561363550999886
Run 37, Time = 8.291426864999949
Run 38, Time = 7.917966033999846
Run 39, Time = 8.145350043999997
Run 40, Time = 7.921112226999867
Run 41, Time = 8.313649267000073
Run 42, Time = 8.17969005499981
Run 43, Time = 7.878249038999911
Run 44, Time = 8.411402247000069
Run 45, Time = 7.7374950040000385
Run 46, Time = 8.43688754699997
Run 47, Time = 7.933012978000079
Run 48, Time = 8.06297156100004
Run 49, Time = 8.261561208999865
Run 0, Time = 8.098174107999967
Run 1, Time = 8.939220933999877
Run 2, Time = 8.650956104999977
Run 3, Time = 8.8961654740001
Run 4, Time = 8.26655099200002
Run 5, Time = 8.998031456000035
Run 6, Time = 8.253369636999878
Run 7, Time = 8.255376794999847
Run 8, Time = 8.718859076999934
Run 9, Time = 8.450927803000013
Run 10, Time = 8.928582134999942
Run 11, Time = 8.437361484000121
Run 12, Time = 8.625732916999823
Run 13, Time = 8.245156065000174
Run 14, Time = 8.793231133000063
Run 15, Time = 8.852361877000021
Run 16, Time = 8.048596551999708
Run 17, Time = 8.609633605999989
Run 18, Time = 8.076272760999927
Run 19, Time = 8.835157334000087
Run 20, Time = 8.180580662000011
Run 21, Time = 8.779927974000202
Run 22, Time = 8.037081460000081
Run 23, Time = 8.800920826000038
Run 24, Time = 8.442641246999756
Run 25, Time = 8.95359244500014
Run 26, Time = 8.295502774999932
Run 27, Time = 8.864517339000031
Run 28, Time = 8.577907948999837
Run 29, Time = 8.973725277000085
Run 30, Time = 8.565072515000338
Run 31, Time = 8.68817258099989
Run 32, Time = 8.36250912899959
Run 33, Time = 9.144126222000068
Run 34, Time = 8.53717218599968
Run 35, Time = 9.135442131999753
Run 36, Time = 8.071064444000058
Run 37, Time = 9.051309038
Run 38, Time = 8.476267272999849
Run 39, Time = 9.124295311999958
Run 40, Time = 8.572279539000192
Run 41, Time = 8.975985329000196
Run 42, Time = 8.479814214000271
Run 43, Time = 9.174242952999975
Run 44, Time = 8.623297421999723
Run 45, Time = 9.120853202000035
Run 46, Time = 8.411955800000214
Run 47, Time = 8.943817929000033
Run 48, Time = 8.165467016000093
Run 49, Time = 8.800817599999846
Run 0, Time = 9.021583066999938
Run 1, Time = 8.802350817999923
Run 2, Time = 9.037099833000411
Run 3, Time = 9.156469485999878
Run 4, Time = 8.77694276300008
Run 5, Time = 8.818309328000396
Run 6, Time = 9.43073784499984
Run 7, Time = 9.077622510999845
Run 8, Time = 9.245971390999784
Run 9, Time = 9.18713621400002
Run 10, Time = 9.515202474000034
Run 11, Time = 8.831960782999886
Run 12, Time = 9.426679738000075
Run 13, Time = 8.65448250899999
Run 14, Time = 9.620889591999912
Run 15, Time = 9.123914399000114
Run 16, Time = 9.60027960699972
Run 17, Time = 8.77102891300001
Run 18, Time = 9.72532236799998
Run 19, Time = 8.689747771999919
Run 20, Time = 8.714477183999861
Run 21, Time = 8.634994517999985
Run 22, Time = 8.935733772000276
Run 23, Time = 8.824228345999927
Run 24, Time = 9.252604810999856
Run 25, Time = 9.342807709000226
Run 26, Time = 8.581241943999885
Run 27, Time = 9.617375477000223
Run 28, Time = 8.96693855400008
Run 29, Time = 9.38932022400013
Run 30, Time = 8.74823639899978
Run 31, Time = 8.94424842799981
Run 32, Time = 8.80111652000005
Run 33, Time = 9.16224449099991
Run 34, Time = 9.441087780000089
Run 35, Time = 9.160287059999973
Run 36, Time = 9.513293720999627
Run 37, Time = 8.706835330999638
Run 38, Time = 9.48293415299986
Run 39, Time = 8.845837265999762
Run 40, Time = 8.913891582999895
Run 41, Time = 8.685684777000006
Run 42, Time = 9.051081775000057
Run 43, Time = 9.382175010000083
Run 44, Time = 8.943660018000173
Run 45, Time = 9.709412397000051
Run 46, Time = 9.047435240999675
Run 47, Time = 9.05219364200002
Run 48, Time = 9.11207063699976
Run 49, Time = 8.6403993670001
Run 0, Time = 11.337999664000108
Run 1, Time = 11.056327260000216
Run 2, Time = 11.074074047000067
Run 3, Time = 10.728730260999782
Run 4, Time = 10.973965262000092
Run 5, Time = 10.635997795000094
Run 6, Time = 10.847779763999824
Run 7, Time = 11.51771207899992
Run 8, Time = 10.569134963999659
Run 9, Time = 11.250704242999745
Run 10, Time = 11.0099893470001
Run 11, Time = 10.789918168999975
Run 12, Time = 11.224355848999949
Run 13, Time = 10.660844540000198
Run 14, Time = 11.298930165999991
Run 15, Time = 10.571942987000057
Run 16, Time = 10.708564045999992
Run 17, Time = 11.54356516300004
Run 18, Time = 10.847945914999855
Run 19, Time = 10.819377766999878
Run 20, Time = 10.85085828199999
Run 21, Time = 11.013160684000013
Run 22, Time = 11.1767229459997
Run 23, Time = 10.749715293000008
Run 24, Time = 11.49226211899986
Run 25, Time = 10.476302206000128
Run 26, Time = 10.758301326000037
Run 27, Time = 11.451258377000158
Run 28, Time = 11.054855082999893
Run 29, Time = 11.05177970800014
Run 30, Time = 11.658576951999748
Run 31, Time = 10.724670619000335
Run 32, Time = 11.600362240999857
Run 33, Time = 10.86003335300029
Run 34, Time = 10.604215917000147
Run 35, Time = 11.659685815000103
Run 36, Time = 10.545390726999813
Run 37, Time = 10.96505321199993
Run 38, Time = 11.327550903999963
Run 39, Time = 10.497540060999654
Run 40, Time = 11.771762470999874
Run 41, Time = 10.553298396000173
Run 42, Time = 11.195172123000248
Run 43, Time = 11.591622418000043
Run 44, Time = 10.48605437299966
Run 45, Time = 10.84818169800019
Run 46, Time = 10.976000636000208
Run 47, Time = 11.156959712000116
Run 48, Time = 11.686241427999903
Run 49, Time = 10.774179379000088

In [12]:
# 4DVar
out_dict_list_4dvar = []
random_seed_list = np.arange(num_runs)+102
system_dim_list = [6, 20, 36, 72, 144, 256]

for system_dim in system_dim_list:
    for i in range(num_runs):
        obs_location_count = int(system_dim/2)
        random_seed = system_dim + random_seed_list[i]
        run_dict = dict(system_dim=system_dim, 
            nr_steps=nr_steps,
            spinup_size=spinup_size,
            valid_size=valid_size,
            transient_size=transient_size,
            test_size=test_size,
            test_run=True,
            delta_t=delta_t,
            obs_location_count=obs_location_count,
            obs_sd=obs_sd,
            sigma_bg_multiplier=5*obs_sd,
            sigma_obs=sigma_obs,
            analysis_window=analysis_window,
            analysis_time_in_window=analysis_time_in_window,
            random_seed=random_seed,
            n_outer_loops = n_outer_loops)
        out_4dvar, error_4dvar, obs_vec_l96, nr_eval, da_time = run_4dvar(**run_dict)
        run_dict['time'] = da_time
        run_dict['rmse'] = error_4dvar
        run_dict['run_num'] = i
        print('Run {}, Time = {}'.format(i,run_dict['time']))
        out_dict_list_4dvar.append(run_dict)
        
var4d_df_time =  pd.DataFrame(out_dict_list_4dvar)
var4d_df_time.to_csv('./out_rev/l96/var4d_systemdim_test_{}.csv'.format(output_suffix))

Run 0, Time = 7.955367652999939
Run 1, Time = 8.700067325999953
Run 2, Time = 8.01865204700016
Run 3, Time = 7.981755926999995
Run 4, Time = 8.861616913000034
Run 5, Time = 8.02786978999984
Run 6, Time = 7.696603769999911
Run 7, Time = 7.945742597999924
Run 8, Time = 7.669664310999906
Run 9, Time = 7.918389610999839
Run 10, Time = 7.695635843999753
Run 11, Time = 7.947549381999579
Run 12, Time = 7.7652997149998555
Run 13, Time = 7.78310048900039
Run 14, Time = 8.397238012999878
Run 15, Time = 7.812853978000021
Run 16, Time = 7.84215971499998
Run 17, Time = 8.845600783999544
Run 18, Time = 7.866669129000002
Run 19, Time = 7.805695423000543
Run 20, Time = 8.870478607999758
Run 21, Time = 7.762642756999412
Run 22, Time = 7.66334615300002
Run 23, Time = 7.707393423000212
Run 24, Time = 8.475932385000306
Run 25, Time = 7.592664489000526
Run 26, Time = 7.62445083700004
Run 27, Time = 8.794338597000205
Run 28, Time = 8.032549970000218
Run 29, Time = 8.057945943999584
Run 30, Time = 8.763486092000676
Run 31, Time = 7.925737644000037
Run 32, Time = 8.015423509999891
Run 33, Time = 7.77539508100017
Run 34, Time = 8.032733860999542
Run 35, Time = 7.670570287000373
Run 36, Time = 7.857000631999654
Run 37, Time = 8.730968999000652
Run 38, Time = 7.580441490999874
Run 39, Time = 7.78253771099935
Run 40, Time = 7.753310473999591
Run 41, Time = 7.831379561000176
Run 42, Time = 7.8119576389999565
Run 43, Time = 7.865507255000011
Run 44, Time = 8.439772529000038
Run 45, Time = 7.619331917000636
Run 46, Time = 7.936716497000816
Run 47, Time = 8.344483396000214
Run 48, Time = 7.716596221000145
Run 49, Time = 7.566895076999572
Run 0, Time = 8.558334052999271
Run 1, Time = 9.540692802000194
Run 2, Time = 8.908100722999734
Run 3, Time = 8.719279865000317
Run 4, Time = 9.162155164999604
Run 5, Time = 8.404398871999547
Run 6, Time = 8.685684566999953
Run 7, Time = 8.515744782000183
Run 8, Time = 9.526341400999627
Run 9, Time = 8.639557225000317
Run 10, Time = 8.634957641000256
Run 11, Time = 9.378898003999893
Run 12, Time = 8.722333310000067
Run 13, Time = 8.537771001000692
Run 14, Time = 8.500698183999702
Run 15, Time = 9.565315566999743
Run 16, Time = 8.715126005999991
Run 17, Time = 8.509238331999768
Run 18, Time = 8.506870584999888
Run 19, Time = 9.604203130000315
Run 20, Time = 8.733598439999696
Run 21, Time = 8.421101677000479
Run 22, Time = 9.410736523000196
Run 23, Time = 8.377310373
Run 24, Time = 8.905063900999266
Run 25, Time = 8.518458870000359
Run 26, Time = 9.637601475999872
Run 27, Time = 8.62352321599974
Run 28, Time = 8.702742442999806
Run 29, Time = 8.648347262999778
Run 30, Time = 9.668897331000153
Run 31, Time = 8.60730203500043
Run 32, Time = 8.800244136999936
Run 33, Time = 8.676770213000054
Run 34, Time = 9.631995205999374
Run 35, Time = 8.42839795800046
Run 36, Time = 8.535368124000343
Run 37, Time = 8.723657702999844
Run 38, Time = 9.337285527999484
Run 39, Time = 8.310007823999513
Run 40, Time = 8.367402460999983
Run 41, Time = 8.75381668800037
Run 42, Time = 8.627850071000466
Run 43, Time = 8.621129627999835
Run 44, Time = 8.463665176999712
Run 45, Time = 9.425613615999282
Run 46, Time = 8.252394862999608
Run 47, Time = 8.555839824000032
Run 48, Time = 8.499417371999698
Run 49, Time = 9.369289291000314
Run 0, Time = 10.250321089999488
Run 1, Time = 10.285708224999325
Run 2, Time = 10.255349287000172
Run 3, Time = 10.895425517000149
Run 4, Time = 10.350661118000062
Run 5, Time = 10.13032915399981
Run 6, Time = 10.503475700000308
Run 7, Time = 11.354050503999133
Run 8, Time = 10.259632350000174
Run 9, Time = 10.122224044999712
Run 10, Time = 10.078445871999975
Run 11, Time = 10.157341735000045
Run 12, Time = 10.35611834700012
Run 13, Time = 9.959094308000203
Run 14, Time = 10.235147451000557
Run 15, Time = 10.428583607999826
Run 16, Time = 10.323470720999467
Run 17, Time = 10.315975253999568
Run 18, Time = 10.218660105999334
Run 19, Time = 10.397660423999696
Run 20, Time = 10.029170519999752
Run 21, Time = 10.031334680999862
Run 22, Time = 10.07176195700049
Run 23, Time = 10.368899793999844
Run 24, Time = 10.542014617999484
Run 25, Time = 10.046859408999808
Run 26, Time = 10.484824473000117
Run 27, Time = 10.231106595999336
Run 28, Time = 10.463933867999913
Run 29, Time = 10.178849525999794
Run 30, Time = 10.139965244999985
Run 31, Time = 10.161872386000141
Run 32, Time = 11.367124094999781
Run 33, Time = 10.05281858499984
Run 34, Time = 10.018704859000536
Run 35, Time = 10.39132550300019
Run 36, Time = 11.68342118199962
Run 37, Time = 10.400748020999345
Run 38, Time = 10.470922919000259
Run 39, Time = 11.059011456000007
Run 40, Time = 12.163305463999677
Run 41, Time = 10.510982202000378
Run 42, Time = 10.455238743000336
Run 43, Time = 10.093811991999246
Run 44, Time = 10.252038197999354
Run 45, Time = 10.5879242660003
Run 46, Time = 10.494560926999839
Run 47, Time = 10.151627561000168
Run 48, Time = 10.16437904599934
Run 49, Time = 11.243213456000376
Run 0, Time = 19.455999787999644
Run 1, Time = 19.818514591000167
Run 2, Time = 19.580813680000574
Run 3, Time = 20.40961131700078
Run 4, Time = 19.482094170999517
Run 5, Time = 19.57177493800009
Run 6, Time = 19.65249979500004
Run 7, Time = 19.283415824999793
Run 8, Time = 19.74775645200043
Run 9, Time = 19.470647314000416
Run 10, Time = 19.70808129299985
Run 11, Time = 19.613238234000164
Run 12, Time = 20.893367650000073
Run 13, Time = 19.726683840000078
Run 14, Time = 19.667139080000197
Run 15, Time = 20.06568998199964
Run 16, Time = 20.826654345999486
Run 17, Time = 19.724843252999563
Run 18, Time = 19.851398767999854
Run 19, Time = 19.666068977000577
Run 20, Time = 19.902625824000097
Run 21, Time = 20.802449859000262
Run 22, Time = 19.774423529999694
Run 23, Time = 19.476131153000097
Run 24, Time = 19.237281497999902
Run 25, Time = 20.542935953999404
Run 26, Time = 19.377723624000282
Run 27, Time = 19.723353895999935
Run 28, Time = 19.538740463000067
Run 29, Time = 20.47035147399947
Run 30, Time = 20.543588266999905
Run 31, Time = 19.657978465999804
Run 32, Time = 19.50752981400001
Run 33, Time = 19.77754241599996
Run 34, Time = 20.671588999999585
Run 35, Time = 19.62887652400059
Run 36, Time = 19.230864096000005
Run 37, Time = 19.84144175900019
Run 38, Time = 19.25003570699937
Run 39, Time = 21.22207036800046
Run 40, Time = 19.46674195000014
Run 41, Time = 19.47738109599959
Run 42, Time = 19.508189111999855
Run 43, Time = 20.862091419000535
Run 44, Time = 19.80602878100035
Run 45, Time = 19.670187147000433
Run 46, Time = 19.16110160900007
Run 47, Time = 19.664380922999953
Run 48, Time = 21.361092907000057
Run 49, Time = 19.248704749000353
Run 0, Time = 55.9261652389996
Run 1, Time = 57.74275482899975
Run 2, Time = 58.27555338399998
Run 3, Time = 56.92304118999982
Run 4, Time = 57.38770336500056
Run 5, Time = 56.63788931199997
Run 6, Time = 56.220491838999806
Run 7, Time = 58.57614366800044
Run 8, Time = 56.648574484000164
Run 9, Time = 56.48415436600044
Run 10, Time = 56.47143235299973
Run 11, Time = 57.41004519600028
Run 12, Time = 57.06951603400012
Run 13, Time = 56.50033029000042
Run 14, Time = 56.76852772700022
Run 15, Time = 55.65183206800066
Run 16, Time = 56.425039405999996
Run 17, Time = 57.71154850899984
Run 18, Time = 56.39609607199964
Run 19, Time = 56.62337916300021
Run 20, Time = 56.48008096400008
Run 21, Time = 57.31965854599912
Run 22, Time = 57.72209141500025
Run 23, Time = 55.89183200199841
Run 24, Time = 56.76511718599977
Run 25, Time = 57.0048714200002
Run 26, Time = 56.43997823900099
Run 27, Time = 57.328342356000576
Run 28, Time = 56.947550953000245
Run 29, Time = 56.69255701199836
Run 30, Time = 57.18520430299941
Run 31, Time = 57.83199468999919
Run 32, Time = 56.59805931600022
Run 33, Time = 55.968266879999646
Run 34, Time = 56.503705491999426
Run 35, Time = 56.04507980700146
Run 36, Time = 57.204956571000366
Run 37, Time = 57.3620639260007
Run 38, Time = 56.44433386700075
Run 39, Time = 56.99968810700011
Run 40, Time = 57.295234688001074
Run 41, Time = 57.909672109000894
Run 42, Time = 56.10826446699866
Run 43, Time = 56.4282724120003
Run 44, Time = 56.288251009000305
Run 45, Time = 55.94470185600039
Run 46, Time = 58.26221195299877
Run 47, Time = 56.07802684199851
Run 48, Time = 56.3159748500002
Run 49, Time = 56.4982507069999
Run 0, Time = 153.6356821219997
Run 1, Time = 156.00804290199994
Run 2, Time = 158.71000853499936
Run 3, Time = 155.65828565899938
Run 4, Time = 154.515118755
Run 5, Time = 154.62332238100134
Run 6, Time = 155.9350340689998
Run 7, Time = 158.4800334270003
Run 8, Time = 154.89668553199954
Run 9, Time = 155.5756306080002
Run 10, Time = 153.01511127199956
Run 11, Time = 154.8901552669995
Run 12, Time = 157.49303744999997
Run 13, Time = 153.6436249899998
Run 14, Time = 155.1531626849992
Run 15, Time = 157.62737561799986
Run 16, Time = 152.26135728300142
Run 17, Time = 159.63947920200008
Run 18, Time = 155.25738433199876
Run 19, Time = 154.5971638840001
Run 20, Time = 155.370814504
Run 21, Time = 154.3280848459999
Run 22, Time = 153.91975747300057
Run 23, Time = 156.3640676670002
Run 24, Time = 155.9123042020001
Run 25, Time = 153.8938480279994
Run 26, Time = 155.98966216900044
Run 27, Time = 156.33836558099938
Run 28, Time = 155.68130159400062
Run 29, Time = 153.94848695399924
Run 30, Time = 155.14410641299946
Run 31, Time = 157.20803293500103
Run 32, Time = 155.8016386829986
Run 33, Time = 155.92434854800013
Run 34, Time = 155.07722018499953
Run 35, Time = 153.9003581800007
Run 36, Time = 154.31169360100102
Run 37, Time = 158.76646933099983
Run 38, Time = 156.31327823399988
Run 39, Time = 155.4286100979989
Run 40, Time = 155.5303473640015
Run 41, Time = 155.5352262410015
Run 42, Time = 155.1527453159979
Run 43, Time = 153.29151969599843
Run 44, Time = 155.498976638999
Run 45, Time = 154.63500955999916
Run 46, Time = 156.0221368679995
Run 47, Time = 153.86162091500228
Run 48, Time = 154.54081001600207
Run 49, Time = 154.37177669599987

### Experiments varying number of observations and obs error - Test Set

In [13]:
# Backprop 4D Var w/ Approximate Hessian

num_runs =  30
system_dim = 36
num_obs_list = [6, 12, 18, 24, 30, 36]
obs_error_list = [0.1, 0.2, 0.3, 0.4, 0.5, 0.75, 1.0, 1.5, 2.0]

for obs_location_count in num_obs_list:
    for obs_sd in obs_error_list:
        
        best_results_filtered = best_results_heatmap.loc[
            (best_results_heatmap['obs_sd'].round(2)==round(obs_sd, 2)) & 
            (best_results_heatmap['num_obs']==obs_location_count)]
        learning_rate = best_results_filtered['config/lr'].values[0]
        lr_decay = best_results_filtered['config/lr_decay'].values[0]
        out_dict_list_bp_obs = []
        
        for i in range(num_runs):
            
            random_seed = 202 + i
            
            run_dict = dict(system_dim=system_dim, 
                nr_steps=nr_steps,
                spinup_size=spinup_size,
                valid_size=valid_size,
                transient_size=transient_size,
                test_size=test_size,
                test_run=True,
                delta_t=delta_t,
                obs_location_count=obs_location_count,
                obs_sd=obs_sd,
                sigma_bg_multiplier=5*obs_sd,
                sigma_obs=obs_sd*1.25,
                analysis_window=analysis_window,
                analysis_time_in_window=analysis_time_in_window,
                random_seed=random_seed,
                num_iters=num_iters,
                learning_rate=learning_rate,
                lr_decay=lr_decay)
            
            out_bp, error_bp, obs_vec_l96, nature_run, da_time = run_backprop_4dvar(**run_dict)
            
            run_dict['time'] = da_time
            run_dict['rmse'] = error_bp
            run_dict['run_num'] = i
                        
            out_dict_list_bp_obs.append(run_dict)
            
        bp_df_obs = pd.DataFrame(out_dict_list_bp_obs)
        out_csv = './out_rev/l96/bp_heatmap_test_{}.csv'.format(output_suffix)
        bp_df_obs.to_csv(out_csv, mode='a',
                            header=(not os.path.isfile(out_csv)),
                            index=False)

In [14]:
# 4DVar

num_runs = 30
system_dim = 36
num_obs_list = [6, 12, 18, 24, 30, 36]
obs_error_list = [0.1, 0.2, 0.3, 0.4, 0.5, 0.75, 1.0, 1.5, 2.0]


for obs_location_count in num_obs_list:
    for obs_sd in obs_error_list:
        
        out_dict_list_4dvar_obs = []
        
        for i in range(num_runs):
            
            random_seed = 202 + i
            
            run_dict = dict(system_dim=system_dim, 
                nr_steps=nr_steps,
                spinup_size=spinup_size,
                valid_size=valid_size,
                transient_size=transient_size,
                test_size=test_size,
                test_run=True,
                delta_t=delta_t,
                obs_location_count=obs_location_count,
                obs_sd=obs_sd,
                sigma_bg_multiplier=5*obs_sd,
                sigma_obs=obs_sd*1.25,
                analysis_window=analysis_window,
                analysis_time_in_window=analysis_time_in_window,
                random_seed=random_seed,
                n_outer_loops = n_outer_loops)
            
            out_4dvar, error_4dvar, obs_vec_l96, nature_run, da_time = run_4dvar(**run_dict)
            
            run_dict['time'] = da_time
            run_dict['rmse'] = error_4dvar
            run_dict['run_num'] = i
            
            out_dict_list_4dvar_obs.append(run_dict)
            
        var4d_df_obs =  pd.DataFrame(out_dict_list_4dvar_obs)
        out_csv = './out_rev/l96/var4d_heatmap_test_{}.csv'.format(output_suffix)
        var4d_df_obs.to_csv(out_csv, mode='a',
                            header=(not os.path.isfile(out_csv)),
                            index=False)

# Run 36D example and save statevectors for later visualization

In [16]:
# Nature run and no-DA baserun
system_dim = 36
i = 0
obs_location_count = 18
obs_sd = 0.5
random_seed = 202 + i

run_dict = dict(system_dim=system_dim, 
                nr_steps=nr_steps,
                spinup_size=spinup_size,
                valid_size=valid_size,
                transient_size=transient_size,
                test_size=test_size,
                test_run=True,
                delta_t=delta_t,
                random_seed=random_seed,
                sigma_bg_multiplier=5*obs_sd)

out_baserun, error_baserun, nature_run, da_time = run_baserun(**run_dict)

run_dict['time'] = da_time
run_dict['rmse'] = error_baserun
run_dict['run_num'] = i

print('Run {}, Time = {}'.format(i,run_dict['time']))
print(obs_location_count, obs_sd, error_baserun)

# Write statevecs
out_file = './out_rev/l96/l96_baserun_results_18obs_36dim_{}.pkl'.format(output_suffix)
with open(out_file, 'wb') as f: 
     pickle.dump(out_baserun, f) 
f.close()

out_file = './out_rev/l96/l96_baserun_nr_18obs_36dim_{}.pkl'.format(output_suffix)
with open(out_file, 'wb') as f: 
     pickle.dump(nature_run, f) 
f.close()

Run 0, Time = 1.8246347570093349
18 0.5 4.961939524549766

In [17]:
# 4DVar
system_dim = 36
i = 0
obs_location_count = 18
obs_sd = 0.5
random_seed = 202 + i

run_dict = dict(system_dim=system_dim, 
                nr_steps=nr_steps,
                spinup_size=spinup_size,
                valid_size=valid_size,
                transient_size=transient_size,
                test_size=test_size,
                test_run=True,
                delta_t=delta_t,
                obs_location_count=obs_location_count,
                obs_sd=obs_sd,
                sigma_bg_multiplier=5*obs_sd,
                sigma_obs=obs_sd*1.25,
                analysis_window=analysis_window,
                analysis_time_in_window=analysis_time_in_window,
                random_seed=random_seed,
                n_outer_loops = n_outer_loops)

out_4dvar, error_4dvar, obs_vec_l96, nature_run, da_time = run_4dvar(**run_dict)

run_dict['time'] = da_time
run_dict['rmse'] = error_4dvar
run_dict['run_num'] = i

print('Run {}, Time = {}'.format(i,run_dict['time']))
print(obs_location_count, obs_sd, error_4dvar)

# Write statevecs
out_file = './out_rev/l96/l96_4dvar_results_18obs_36dim_{}.pkl'.format(output_suffix)
with open(out_file, 'wb') as f: 
     pickle.dump(out_4dvar, f) 
f.close()

out_file = './out_rev/l96/l96_4dvar_nr_18obs_36dim_{}.pkl'.format(output_suffix)
with open(out_file, 'wb') as f: 
     pickle.dump(nature_run, f) 
f.close()

out_file = './out_rev/l96/l96_4dvar_obsvec_18obs_36dim_{}.pkl'.format(output_suffix)
with open(out_file, 'wb') as f: 
     pickle.dump(obs_vec_l96, f) 
f.close()

Run 0, Time = 15.21421150000242
18 0.5 1.0561442299437243

In [18]:
# Backprop 4DVar w/ approximate Hessian

system_dim = 36
i = 0
obs_location_count = 18
obs_sd = 0.5

best_results_filtered = best_results_heatmap.loc[
    (best_results_heatmap['obs_sd'].round(2)==round(obs_sd, 2)) & 
    (best_results_heatmap['num_obs']==obs_location_count)]
learning_rate = best_results_filtered['config/lr'].values[0]
lr_decay = best_results_filtered['config/lr_decay'].values[0]

random_seed = 202 + i

run_dict = dict(system_dim=system_dim, 
    nr_steps=nr_steps,
    spinup_size=spinup_size,
    valid_size=valid_size,
    transient_size=transient_size,
    test_size=test_size,
    test_run=True,
    delta_t=delta_t,
    obs_location_count=obs_location_count,
    obs_sd=obs_sd,
    sigma_bg_multiplier=5*obs_sd,
    sigma_obs=obs_sd*1.25,
    analysis_window=analysis_window,
    analysis_time_in_window=analysis_time_in_window,
    random_seed=random_seed,
    num_iters=num_iters,
    learning_rate=learning_rate,
    lr_decay=lr_decay)

out_bp, error_bp, obs_vec_l96, nature_run, da_time = run_backprop_4dvar(**run_dict)
run_dict['time'] = da_time
run_dict['rmse'] = error_bp
run_dict['run_num'] = i

print('Run {}, Time = {}'.format(i,run_dict['time']))
print(obs_location_count, obs_sd, error_bp)

# Write statevecs
out_file = './out_rev/l96/l96_bp_results_18obs_36dim_{}.pkl'.format(output_suffix)
with open(out_file, 'wb') as f:  
     pickle.dump(out_bp, f) 
f.close()

Run 0, Time = 13.205944904999342
18 0.5 0.9011262709305115